### ISSUE TITLE
Переосмыслить UX

### ISSUE THREAD

**Issue by slartus** [AlexGladkov/VkTube-Android#29]
Короче, на главной надо выводить группы и входить в них, чтобы увидеть видео. Иначе, если групп много, то ждать очень долго(100 групп~1мин). 
если больше 100 то видео из них сейчас не будут показываться. 

Также есть ограничение на кол-во запросов одного метода в секунду (3) и ограничение на общее количество запросов метода (не указано сколько-неявное).
https://vk.com/dev/api_requests

При этом в группе вообще может не быть видео. 

Или вариант: при первом открытии выбрать из каких групп хочешь видеть видео в ленте и ограничить 20ю, например (~3-5 сек ожидания)

**Comment by mironoff2007** [comment]
Да, с эти нужно что-то делать. Но у меня почему-то ошибка не 6: "Too many requests per second.", а 29:"Rate limit reached"

**Comment by slartus** [comment]
ограничение на общее количество запросов метода (не указано сколько-неявное).
https://vk.com/dev/api_requests

**Comment by mironoff2007** [comment]
Да, но по идее должен капчу спросить. И странно, что со вчерашнего вечера так и не снялся лимит, я даже 1 запрос video.get не могу выполнить, а группы получает.
Наверное, надо попробовать execute метод

**Comment by mironoff2007** [comment]
Пример запроса 
https://dev.vk.com/method/execute

**return [ API.video.get({ "owner_id": -113499203,"count": 2 }), API.video.get({ "owner_id": -25232578, "count": 2 }) ];**

Запрашивает видео сразу из 2 групп.
"Внутри code может содержаться не более 25 обращений к методам API."

Как выглядит ответ. Тут и количество видео в группе. 
![image](https://user-images.githubusercontent.com/18057056/160294644-4437ce27-fbf2-40a1-9f30-07bee08c796d.png)

Думаю, что можно с этим методом оптимизировать запросы. Можно остановиться пока на 25 группах, сделать белый список групп до 25.

**Comment by slartus** [comment]
победил все проблемы, связанные с execute. обновил PR #25
